version: "3"

volumes:
  mongo:
  keydb:

services:
  mongo:
    container_name: mongo
    env_file:
      - ./.env
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    command: mongod

  keydb:
    container_name: keydb
    env_file:
      - ./.env
    image: eqalpha/keydb:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - keydb:/data
    command: keydb-server
